project:
  type: website
  output-dir: docs

website:
  title: "Home"
  sidebar:
    style: "docked"
    contents: auto
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: research/index.qmd
        text: Research
      - href: cv.pdf
        text: CV

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor:
  render-on-save: true
